POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "liliia@gmail.com",
  "password": "lilu1234"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "maria@gmail.com",
  "password": "maria1234"
}

### add event
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Team Building",
  "date": "06.08.2023"
}

###

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Birthday of boss",
  "date": "15.09.2023"
}

### Получение всех пользователей
GET http://localhost:8080/api/users

### Получение всех событий
GET http://localhost:8080/api/events

### Удаление пользователя
DELETE http://localhost:8080/api/users/2

### Удаление события
DELETE http://localhost:8080/api/events/1

### Обновление пользователя 1
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "newRole" : "MANAGER",
  "newState" : "CONFIRMED"
}

### Обновление пользователя 2
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "newRole" : "ADMIN",
  "newState" : "CONFIRMED"
}

### обновление события
PUT http://localhost:8080/api/events/2
Content-Type: application/json

{
  "newDate" : "05.01.2023"
}

### Get user
GET http://localhost:8080/api/users/1

### Get event
GET http://localhost:8080/api/events/1